version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    container_name: backend
    image: task4_backend
    ports:
      - "5252:5252"

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: frontend
    image: task4_frontend
    ports:
      - "9000:9000"
    depends_on:
      - backend
